
export const listInventoryFerrePal = [
    'Todos',
    'Llaves convinadas de jardin chorro angular y esfera',
    'Abrazaderas',
    'Aceites aceiteras grasa lubricante y amarrador de varillas',
    'Alambres variados',
    'Apagadores y contactos modus bticino',
    'arcos para segueta',
    'Articulos de seguridad',
    'Bisagras rectangulares y especiales',
    'Bombas y accesorios',
    'Brocas',
    'Brichas BYP',
    'Brochas pretul',
    'Cable TWH 1 polo IUSA',
    'Cadenas accesorios',
    'Calentadores y boilers',
    'Calibradores',
    'Candados Antipalanca',
    'Carretillas llantas y accesorios',
    'Centros de carga y bases para medidor',
    'Cerrajeria accesorios',
    'Cespol para lavado fregadero coladeras y tapas',
    'Chalupas botes y cajas y tapas de registro'
]